inherit_from: configs/ATLAS/atlas_base.yaml

cam:
  H: 540
  W: 960
  fx: 587.36083984375
  fy: 587.36083984375
  cx: 529.1632080078125
  cy: 271.7477111816406

data:
  image_input_folder: data/breathing/dynamic_breathing_half_res
  transforms: data/breathing/dynamic_breathing_half_res/reduced_transforms.json
  mesh: data/breathing/CT/ImFusionExport_abdominal_cavity_coarse.obj
  output: output/ATLAS/breathing/dynamic_breathing

model:
  ARAP:
    active: True