name: bridgesplat
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision
  - pytorch-cuda=11.8
  - cmake
  - ninja
  - gcc_linux-64=10
  - gxx_linux-64=10
  - eigen
  - xorg-x11-server-xvfb-cos7-x86_64
  - pip
  - pip:
    - wandb
    - scipy
    - numpy==1.26.0
    - pillow==9
    - tqdm
    - pyvista
    - meshio
    - vtk
    - opencv-python
    - imageio
    - matplotlib
    - uvicorn
    - tensorboard
    - xvfbwrapper