inherit_from: configs/SOFA/sofa_liver.yaml

data:
  image_input_folder: data/Synthetic/liver_left
  mesh: data/Synthetic/liver_left/mesh_0000.obj
  transforms: data/Synthetic/liver_left/transforms.json
  output: output/SOFA/liver_left