inherit_from: configs/SOFA/sofa_liver.yaml

data:
  image_input_folder: data/Synthetic/liver_in
  mesh: data/Synthetic/liver_in/mesh_0000.obj
  transforms: data/Synthetic/liver_in/transforms.json
  output: output/SOFA/liver_in