inherit_from: configs/SOFA/sofa_liver.yaml

data:
  image_input_folder: data/Synthetic/liver_circle
  mesh: data/Synthetic/liver_circle/mesh_0000.obj
  transforms: data/Synthetic/liver_circle/transforms.json
  output: output/SOFA/liver_circle