inherit_from: configs/SOFA/sofa_liver.yaml

data:
  image_input_folder: data/Synthetic/liver_up
  mesh: data/Synthetic/liver_up/mesh_0000.obj
  transforms: data/Synthetic/liver_up/transforms.json
  output: output/SOFA/liver_up